package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity for a user-defined price alert (Celina 3.2), stored in the
 * {@code price_alerts} table.
 *
 * <p>An alert links one user to one {@link Listing} and a {@link PriceAlertCondition}
 * with a numeric threshold. The {@code stock-service} scheduler evaluates every
 * {@code active} alert after each market-data refresh and publishes a
 * {@code price.alert_triggered} notification when the condition is met.
 *
 * <p>{@code lastTriggeredAt} is used both for an in-app audit trail and for
 * debouncing: an alert is not re-fired while its condition stays continuously
 * satisfied — it fires again only after the price has moved back out of the
 * trigger zone and the condition is re-met.
 */
@Entity
@Table(name = "price_alerts")
@Getter
@Setter
public class PriceAlert {

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the user that owns the alert, taken from the JWT {@code id} claim.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * Identity space the {@code userId} belongs to — {@code CLIENT} or {@code EMPLOYEE}.
     * Derived from the creating user's JWT role; needed so the notification-service
     * can scope the in-app row to the correct id space.
     */
    @Column(name = "recipient_type", nullable = false, length = 16)
    private String recipientType;

    /**
     * Identifier of the {@link Listing} whose price is tracked by this alert.
     */
    @Column(name = "listing_id", nullable = false)
    private Long listingId;

    /**
     * Trigger condition evaluated against the listing price.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "condition", nullable = false, length = 32)
    private PriceAlertCondition condition;

    /**
     * Numeric threshold compared against the listing price (or intraday percentage
     * drop magnitude for {@link PriceAlertCondition#PCT_DROP_INTRADAY}).
     */
    @Column(name = "threshold", nullable = false, precision = 19, scale = 4)
    private BigDecimal threshold;

    /**
     * Preferred delivery channel — {@code EMAIL}, {@code PUSH}, {@code IN_APP} or {@code ALL}.
     */
    @Column(name = "notification_type", nullable = false, length = 16)
    private String notificationType;

    /**
     * Whether the alert is currently active and should be evaluated.
     */
    @Column(name = "active", nullable = false)
    private boolean active = true;

    /**
     * Timestamp when the alert was created.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last time the alert fired, or {@code null} if it has never fired.
     * Used for the debounce rule described on this class.
     */
    @Column(name = "last_triggered_at")
    private LocalDateTime lastTriggeredAt;
}
