package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity for a user-defined watchlist (Celina 3.4), stored in the
 * {@code watchlists} table.
 *
 * <p>A watchlist is a personalized, named collection of followed securities
 * that the owner can monitor without buying them. One user may own several
 * watchlists (for example a "tech stocks" list and a "forex pairs" list); the
 * individual followed securities are stored as {@link WatchlistItem} rows that
 * point back to this list through {@code watchlistId}.
 *
 * <p>Every watchlist is scoped to a single owner identified by the JWT
 * {@code id} claim. Callers can never see or mutate another user's watchlists.
 */
@Entity
@Table(name = "watchlists")
@Getter
@Setter
public class Watchlist {

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the user that owns the watchlist, taken from the JWT {@code id} claim.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * Human-readable name shown to the owner, for example {@code "Tech stocks"}.
     */
    @Column(name = "name", nullable = false, length = 128)
    private String name;

    /**
     * Timestamp when the watchlist was created.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
