package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity for a single followed security inside a {@link Watchlist}
 * (Celina 3.4), stored in the {@code watchlist_items} table.
 *
 * <p>Each row links one watchlist to one {@link Listing}. The
 * {@code (watchlist_id, listing_id)} pair is unique so the same security cannot
 * be added twice to the same list.
 *
 * <p>The item only persists the {@code listingId} reference; current market
 * data (ticker, name, price, change, volume and listing type) is resolved from
 * the {@link Listing} entity when the item is served to the API, so the
 * watchlist always reflects the latest market snapshot.
 */
@Entity
@Table(
        name = "watchlist_items",
        uniqueConstraints = @UniqueConstraint(
                name = "uq_watchlist_items_watchlist_listing",
                columnNames = {"watchlist_id", "listing_id"}
        )
)
@Getter
@Setter
public class WatchlistItem {

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the owning {@link Watchlist}.
     */
    @Column(name = "watchlist_id", nullable = false)
    private Long watchlistId;

    /**
     * Identifier of the followed {@link Listing}.
     */
    @Column(name = "listing_id", nullable = false)
    private Long listingId;

    /**
     * Timestamp when the security was added to the watchlist.
     */
    @Column(name = "added_at", nullable = false)
    private LocalDateTime addedAt;
}
