version: "3.9"

services:
  postgres_transaction:
    image: postgres:15
    container_name: postgres_transaction
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TRANSACTION_DB_NAME}
      POSTGRES_USER: ${TRANSACTION_DB_USER}
      POSTGRES_PASSWORD: ${TRANSACTION_DB_PASSWORD}
    ports:
      - "${TRANSACTION_DB_PORT}:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data
    networks:
      - banka-network

volumes:
  postgres_transaction_data:

networks:
  banka-network:
    driver: bridge
