package platform

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

func TestLoadConfigUsesDefaults(t *testing.T) {
	cfg := LoadConfig()

	assert.Equal(t, "8085", cfg.ServerPort)
	assert.Equal(t, "9085", cfg.GRPCPort)
	assert.Equal(t, "postgres", cfg.DBHost)
	assert.Equal(t, "5432", cfg.DBPort)
	assert.Equal(t, "market_service", cfg.DBName)
	assert.Equal(t, "postgres", cfg.DBUser)
	assert.Equal(t, "postgres", cfg.DBPassword)
	assert.Equal(t, "disable", cfg.DBSSLMode)
	assert.Equal(t, "development_market_service_secret_123456", cfg.JWT.Secret)
	assert.Equal(t, "banka1", cfg.JWT.Issuer)
	assert.Equal(t, []string{"http://localhost:4200"}, cfg.CORS.AllowedOrigins)
	assert.Equal(t, []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"}, cfg.CORS.AllowedMethods)
	assert.Equal(t, "https://www.alphavantage.co", cfg.Stock.MarketDataBaseURL)
	assert.Equal(t, 2*time.Second, cfg.Stock.RedisTimeout)
	assert.True(t, cfg.Stock.RefreshEnabled)
	assert.Equal(t, 900000*time.Millisecond, cfg.Stock.RefreshInterval)
	assert.Equal(t, 15*time.Second, cfg.Stock.PriceFeedTTL)
	assert.Equal(t, "https://api.twelvedata.com", cfg.FX.TwelveDataBaseURL)
	assert.Equal(t, "1.0", cfg.FX.MarginPercentage)
	assert.Equal(t, "0.70", cfg.FX.CommissionPercentage)
	assert.True(t, cfg.FX.FetchOnStartup)
	assert.Equal(t, []string{"RSD", "EUR", "CHF", "USD", "GBP", "JPY", "CAD", "AUD"}, cfg.FX.SupportedCurrencies)
}

func TestLoadConfigReadsEnvironmentOverrides(t *testing.T) {
	t.Setenv("SERVER_PORT", "18085")
	t.Setenv("GRPC_PORT", "19085")
	t.Setenv("MARKET_SERVICE_DB_HOST", "db")
	t.Setenv("MARKET_SERVICE_DB_PORT", "15432")
	t.Setenv("MARKET_SERVICE_DB_NAME", "market")
	t.Setenv("MARKET_SERVICE_DB_USER", "market_user")
	t.Setenv("MARKET_SERVICE_DB_PASSWORD", "secret")
	t.Setenv("MARKET_SERVICE_DB_SSLMODE", "require")
	t.Setenv("JWT_SECRET", "jwt-secret")
	t.Setenv("BANKA_SECURITY_ISSUER", "issuer")
	t.Setenv("BANKA_SECURITY_ID_CLAIM", "sub")
	t.Setenv("BANKA_SECURITY_ROLES_CLAIM", "authorities")
	t.Setenv("BANKA_SECURITY_PERMISSIONS_CLAIM", "perms")
	t.Setenv("BANKA_SECURITY_CORS_ALLOWED_ORIGINS", " http://a.test, ,http://b.test ")
	t.Setenv("STOCK_MARKET_DATA_BASE_URL", "https://stocks.test")
	t.Setenv("STOCK_MARKET_DATA_API_KEY", "stock-key")
	t.Setenv("ALPHA_VANTAGE_API_KEY", "alpha-key")
	t.Setenv("STOCK_EXCHANGE_SERVICE_URL", "http://exchange")
	t.Setenv("REDIS_HOST", "redis")
	t.Setenv("REDIS_PORT", "6380")
	t.Setenv("REDIS_TIMEOUT_MS", "150")
	t.Setenv("STOCK_LISTING_REFRESH_ENABLED", "false")
	t.Setenv("STOCK_LISTING_REFRESH_INTERVAL_MS", "300")
	t.Setenv("STOCK_PRICE_CACHE_TTL_SECONDS", "7")
	t.Setenv("STOCK_EXCHANGE_SEED_CSV_LOCATION", "/seed.csv")
	t.Setenv("EXCHANGE_TWELVE_DATA_BASE_URL", "https://fx.test")
	t.Setenv("TWELVE_DATA_API_KEY", "twelve-key")
	t.Setenv("EXCHANGE_MARGIN_PERCENTAGE", "1.5")
	t.Setenv("EXCHANGE_COMMISSION_PERCENTAGE", "0.8")
	t.Setenv("EXCHANGE_RATES_FETCH_ON_STARTUP", "false")
	t.Setenv("EXCHANGE_RATES_FETCH_CRON", "0 15 9 * * *")

	cfg := LoadConfig()

	assert.Equal(t, "18085", cfg.ServerPort)
	assert.Equal(t, "19085", cfg.GRPCPort)
	assert.Equal(t, "postgres://market_user:secret@db:15432/market?sslmode=require", cfg.DatabaseURL())
	assert.Equal(t, "jwt-secret", cfg.JWT.Secret)
	assert.Equal(t, "issuer", cfg.JWT.Issuer)
	assert.Equal(t, "sub", cfg.JWT.IDClaim)
	assert.Equal(t, "authorities", cfg.JWT.RolesClaim)
	assert.Equal(t, "perms", cfg.JWT.PermissionsClaim)
	assert.Equal(t, []string{"http://a.test", "http://b.test"}, cfg.CORS.AllowedOrigins)
	assert.Equal(t, "https://stocks.test", cfg.Stock.MarketDataBaseURL)
	assert.Equal(t, "stock-key", cfg.Stock.MarketDataAPIKey)
	assert.Equal(t, "alpha-key", cfg.Stock.AlphaVantageAPIKey)
	assert.Equal(t, "http://exchange", cfg.Stock.ExchangeServiceBaseURL)
	assert.Equal(t, "redis", cfg.Stock.RedisHost)
	assert.Equal(t, "6380", cfg.Stock.RedisPort)
	assert.Equal(t, 150*time.Millisecond, cfg.Stock.RedisTimeout)
	assert.False(t, cfg.Stock.RefreshEnabled)
	assert.Equal(t, 300*time.Millisecond, cfg.Stock.RefreshInterval)
	assert.Equal(t, 7*time.Second, cfg.Stock.PriceFeedTTL)
	assert.Equal(t, "/seed.csv", cfg.Stock.ExchangeCSVLocation)
	assert.Equal(t, "https://fx.test", cfg.FX.TwelveDataBaseURL)
	assert.Equal(t, "twelve-key", cfg.FX.TwelveDataAPIKey)
	assert.Equal(t, "1.5", cfg.FX.MarginPercentage)
	assert.Equal(t, "0.8", cfg.FX.CommissionPercentage)
	assert.False(t, cfg.FX.FetchOnStartup)
	assert.Equal(t, "0 15 9 * * *", cfg.FX.FetchCron)
}

func TestLoadConfigFallbacksForBlankAndInvalidEnvironment(t *testing.T) {
	t.Setenv("SERVER_PORT", "   ")
	t.Setenv("POSTGRES_SSLMODE", "prefer")
	t.Setenv("REDIS_TIMEOUT_MS", "bad")
	t.Setenv("STOCK_LISTING_REFRESH_ENABLED", "not-bool")
	t.Setenv("EXCHANGE_RATES_FETCH_ON_STARTUP", "not-bool")
	t.Setenv("BANKA_SECURITY_ISSUER_FALLBACK", "fallback-issuer")
	t.Setenv("ALPHA_VANTAGE_API_KEY", "shared-key")

	cfg := LoadConfig()

	assert.Equal(t, "8085", cfg.ServerPort)
	assert.Equal(t, "prefer", cfg.DBSSLMode)
	assert.Equal(t, 2*time.Second, cfg.Stock.RedisTimeout)
	assert.True(t, cfg.Stock.RefreshEnabled)
	assert.True(t, cfg.FX.FetchOnStartup)
	assert.Equal(t, "fallback-issuer", cfg.JWT.Issuer)
	assert.Equal(t, "shared-key", cfg.Stock.MarketDataAPIKey)
	assert.Equal(t, "shared-key", cfg.FX.TwelveDataAPIKey)
}
