package com.banka1.verificationService.model.entity;

import com.banka1.verificationService.crypto.TotpSecretConverter;
import com.banka1.verificationService.model.enums.OperationType;
import com.banka1.verificationService.model.enums.VerificationStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a verification session in the database.
 *
 * Stores a per-session TOTP secret (RFC 6238), session metadata, and state
 * information for two-factor authentication (2FA) operations. Each session is
 * uniquely identified by the combination of clientId, operationType, and
 * relatedEntityId, with a lifecycle controlled by its status and expiration time.
 *
 * <p>WP-6 (Celina 2.1): the verification code is now a standard 30-second TOTP
 * derived from {@link #totpSecret}. The legacy {@link #code} column (an
 * HMAC-SHA256 hash) is retained for back-compat with sessions created before
 * the migration but is no longer written for new sessions.
 *
 * A typical session flow:
 * <ol>
 *   <li>Created with status PENDING, a per-session TOTP secret, and a TTL</li>
 *   <li>User provides the current TOTP code within the TTL window</li>
 *   <li>Status transitions to VERIFIED on match or CANCELLED after 3 failed attempts</li>
 *   <li>Status transitions to EXPIRED if current time passes expiresAt</li>
 * </ol>
 *
 * @see VerificationStatus
 * @see OperationType
 */
@Entity
@Table(name = "verification_sessions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VerificationSession {

    /**
     * Unique identifier for this verification session, auto-generated by the database.
     * Primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ID of the client requesting verification.
     * Used to enforce authorization (client can only verify their own sessions)
     * and to query sessions by client.
     * Non-nullable.
     */
    @Column(nullable = false)
    private Long clientId;

    /**
     * Legacy column: Base64-encoded HMAC-SHA256 hash of a random OTP code.
     *
     * <p>WP-6 (Celina 2.1) replaced random emailed codes with per-session TOTP;
     * new sessions leave this {@code null} and use {@link #totpSecret} instead.
     * The column is retained (nullable) only so verification sessions created
     * before the migration can still be validated against their stored hash.
     */
    @Column(nullable = true)
    private String code;

    /**
     * Per-session TOTP secret (RFC 6238), Base32-encoded in plaintext at the
     * application layer.
     *
     * <p>The current verification code is computed from this secret with a
     * 30-second time step. The secret is encryption-at-rest: {@link TotpSecretConverter}
     * stores an AES-GCM-256 ciphertext in the {@code totp_secret} column and the
     * field never holds plaintext on disk. Nullable for back-compat with legacy
     * sessions that predate the TOTP migration.
     */
    @Convert(converter = TotpSecretConverter.class)
    @Column(name = "totp_secret")
    private String totpSecret;

    /**
     * The type of operation requiring verification (e.g., PAYMENT, TRANSFER).
     * Used to categorize and qualify verification sessions.
     * Non-nullable.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OperationType operationType;

    /**
     * The ID of the entity associated with this verification session (e.g., transaction ID, request ID).
     * Combined with clientId and operationType to uniquely identify a session
     * and prevent duplicate concurrent verifications for the same operation.
     * Non-nullable.
     */
    @Column(nullable = false)
    private String relatedEntityId;

    /**
     * Timestamp when this session was created.
     * Used for auditing and calculating session age.
     * Non-nullable.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this session expires.
     * Typically set to 5 minutes after creation. If the current time passes this
     * timestamp, the session should be transitioned to EXPIRED status.
     * Non-nullable.
     */
    @Column(nullable = false)
    private LocalDateTime expiresAt;

    /**
     * Counter for failed validation attempts.
     * Incremented on each invalid code submission. The session is automatically
     * cancelled when this counter reaches 3.
     * Non-nullable, defaults to 0.
     */
    @Column(nullable = false)
    private int attemptCount;

    /**
     * Current state of the verification session.
     * Transitions: PENDING → VERIFIED/EXPIRED/CANCELLED
     * Non-nullable.
     *
     * @see VerificationStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private VerificationStatus status;
}
